services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN:?}
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      DEBUG: ${DEBUG:-0}
      PERSISTENCE: ${PERSISTENCE:-1}
      SERVICES: sqs,ecs,ec2,ecr,rds,iam,cloudwatch,logs,sts,s3,servicediscovery,elasticloadbalancing,elbv2,route53,kms
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
