storage:
  postgres:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      port:
        env: POSTGRES_PORT

compute_logs:
  module: dagster.core.storage.noop_compute_log_manager
  class: NoOpComputeLogManager

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_taskiq.launcher
  class: TaskiqRunLauncher
  config:
    broker:
      sqs_queue_url:
        env: DAGSTER_TASKIQ_SQS_QUEUE_URL
      aws_region:
        env: AWS_DEFAULT_REGION
      endpoint_url:
        env: DAGSTER_TASKIQ_SQS_ENDPOINT_URL
    default_queue: long-queue

run_monitoring:
  enabled: true
  start_timeout_seconds: 60
  cancel_timeout_seconds: 60
  poll_interval_seconds: 30

telemetry:
  enabled: false
