encryptionsalt: v1:mo3eYhNtJJM=:v1:lma7cNLhkm1Tl+2D:BD0DdjiArlfdmP4OOAWtPGoF0pJlcQ==
config:
  localstack-ecs-sqs:taskiqDemo:
    enabled: true
    queueName: taskiq-demo
    imageTag: taskiq-demo
    apiDesiredCount: 1
    workerDesiredCount: 1
