config:
  localstack-ecs-sqs:project:
    name: dagster-taskiq-demo
    environment: dev
  localstack-ecs-sqs:aws:
    region: us-east-1
    endpoint: http://localhost:4566
    accessKey: test
    secretKey: test
  localstack-ecs-sqs:queue:
    messageRetentionSeconds: 1209600
    visibilityTimeoutSeconds: 900
    dlqVisibilityTimeoutSeconds: 60
    redriveMaxReceiveCount: 3
  localstack-ecs-sqs:database:
    engineVersion: "15.4"
    instanceClass: db.t3.micro
    allocatedStorage: 20
    maxAllocatedStorage: 100
    username: dagster
    password: dagster
    dbName: dagster
  localstack-ecs-sqs:services:
    image: dagster-taskiq:latest
    daemonDesiredCount: 1
    webserverDesiredCount: 1
    workerDesiredCount: 2
encryptionsalt: v1:W5HG4tl7ZDI=:v1:PjS5DICzdqBUXYuD:UfCuZKABu1DqPpjUEMwuKLK5dgjvRQ==
