services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: docker/docker.env
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
    networks:
      - dagster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d dagster"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      LAMBDA_EXECUTOR: local
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - dagster-localstack:/tmp/localstack
    networks:
      - dagster-network

  codelocation:
    profiles:
      - dagster
    build:
      context: ..
      dockerfile: ./example/Dockerfile
    image: dagster-example:latest
    env_file: docker/docker.env
    volumes:
      - ./docker/dagster.yaml:/app/dagster.yaml
    networks:
      - dagster-network
    depends_on:
      - postgresql
      - daemon

  worker-short:
    profiles:
      - dagster
    image: dagster-example:latest
    command: dagster-taskiq worker start -y /app/taskiq.yaml
    restart: on-failure
    env_file: docker/docker.env
    cap_add:
      - SYS_PTRACE
    environment:
      DAGSTER_HOME: /app
    volumes:
      - ./docker/dagster.yaml:/app/dagster.yaml
      - ./docker/taskiq.yaml:/app/taskiq.yaml
    networks:
      - dagster-network
    depends_on:
      - postgresql
      - localstack
      - daemon

  worker-long:
    profiles:
      - dagster
    image: dagster-example:latest
    command: dagster-taskiq worker start -y /app/taskiq.yaml
    restart: on-failure
    env_file: docker/docker.env
    cap_add:
      - SYS_PTRACE
    environment:
      DAGSTER_HOME: /app
    volumes:
      - ./docker/dagster.yaml:/app/dagster.yaml
      - ./docker/taskiq.yaml:/app/taskiq.yaml
    networks:
      - dagster-network
    depends_on:
      - postgresql
      - localstack
      - daemon

  webserver:
    profiles:
      - dagster
    image: dagster-example:latest
    restart: on-failure
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: docker/docker.env
    environment:
      DAGSTER_HOME: /app
    volumes:
      - ./docker/dagster.yaml:/app/dagster.yaml
      - ./docker/workspace.yaml:/app/workspace.yaml
    networks:
      - dagster-network
    depends_on:
      - postgresql

  daemon:
    profiles:
      - dagster
    image: dagster-example:latest
    restart: on-failure
    entrypoint:
      - dagster-daemon
      - run
    env_file: docker/docker.env
    environment:
      DAGSTER_HOME: /app
    volumes:
      - ./docker/dagster.yaml:/app/dagster.yaml
      - ./docker/workspace.yaml:/app/workspace.yaml
    networks:
      - dagster-network
    depends_on:
      - postgresql



volumes:
  dagster-postgres:
  dagster-localstack:

networks:
  dagster-network:
    driver: bridge
