[task_config]
includes = [ "../tasks.toml" ]

[tasks."run:app"]
description = "Run the FastAPI service locally"
run = "uv run taskiq-demo-api"

[tasks."run:worker"]
description = "Run the TaskIQ worker locally"
run = "uv run taskiq-demo-worker"
